In [18]:
import pandas as pd

movies = pd.read_csv("datasets/movies_directors/movies.csv", index_col=0).head(100)
directors = pd.read_csv("datasets/movies_directors/directors.csv", index_col=0).head(30)

df = movies.merge(directors, left_on="director_id", right_on="id", how="outer")

df.shape

(111, 14)

In [11]:
df

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,4763,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Sam Mendes,4764,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Christopher Nolan,4765,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Sam Raimi,4767,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday,Martin Scorsese,4809,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday,Kevin Smith,5369,Male
1462,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday,Uwe Boll,5148,Male
1463,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday,Richard Linklater,5535,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday,Robert Rodriguez,5097,NaN

In [30]:
import pandas as pd

citations = pd.read_csv("datasets/deepscholar-bench/citations.csv")
paper_contents = pd.read_csv("datasets/deepscholar-bench/paper_content.csv")
print(paper_contents.columns)
print(citations.columns)

Index(['arxiv_link', 'arxiv_id', 'publication_date', 'paper_title', 'abstract',
       'related_works_section', 'related_works_length'],
      dtype='object')
Index(['parent_paper_title', 'parent_paper_arxiv_id', 'citation_shorthand',
       'raw_citation_text', 'cited_paper_title', 'cited_paper_arxiv_link',
       'cited_paper_abstract', 'has_metadata', 'is_arxiv_paper',
       'bib_paper_authors', 'bib_paper_year', 'bib_paper_month',
       'bib_paper_url', 'bib_paper_doi', 'bib_paper_journal'],
      dtype='object')

In [34]:
df1 = paper_contents.merge(citations, left_on="arxiv_id", right_on="parent_paper_arxiv_id", how="inner", indicator=True)[["arxiv_id", "paper_title", "parent_paper_arxiv_id", "parent_paper_title", "cited_paper_title"]]
df2 = df1.merge(paper_contents, left_on="cited_paper_title", right_on="paper_title", suffixes=("_x", "_y"), indicator=True)

df1.to_csv("temp.csv")

In [ ]:
cited_papers = pd.DataFrame(citations['cited_paper_title'])
print(cited_papers.shape)
cited_papers.drop_duplicates(subset=['cited_paper_title'], inplace=True)
print(cited_papers.shape)

sampled = cited_papers.sample(28)
print(sampled.shape)

df1 = citations.drop_duplicates(subset='cited_paper_title').merge(sampled, on="cited_paper_title", how="inner")
print(df1.shape)
df1.to_csv("temp.csv")

for size in 
sampled_papers = paper_contents.sample(10)

(1630, 1)
(1552, 1)
(28, 1)
(28, 15)

In [52]:
len(left_papers['arxiv_id'].tolist())

63

In [53]:
from datasets import load_dataset

# Load the dataset
dataset = load_dataset("DeepPavlov/hwu64")

# Get the list of unique labels from the train split
unique_labels = sorted(set(dataset['train']['label']))

# Print them
for i, label in enumerate(unique_labels):
    print(f"{i+1}: {label}")

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/173k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/26.3k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8954 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1076 [00:00<?, ? examples/s]

1: 0
2: 1
3: 2
4: 3
5: 4
6: 5
7: 6
8: 7
9: 8
10: 9
11: 10
12: 11
13: 12
14: 13
15: 14
16: 15
17: 16
18: 17
19: 18
20: 19
21: 20
22: 21
23: 22
24: 23
25: 24
26: 25
27: 26
28: 27
29: 28
30: 29
31: 30
32: 31
33: 32
34: 33
35: 34
36: 35
37: 36
38: 37
39: 38
40: 39
41: 40
42: 41
43: 42
44: 43
45: 44
46: 45
47: 46
48: 47
49: 48
50: 49
51: 50
52: 51
53: 52
54: 53
55: 54
56: 55
57: 56
58: 57
59: 58
60: 59
61: 60
62: 61
63: 62
64: 63

In [ ]:
import pandas as pd 
movies = pd.read_csv("datasets/movies_directors/movies.csv", index_col=0)
directors = pd.read_csv("datasets/movies_directors/directors.csv", index_col=0)

df2 = movies.merge(directors, left_on="director_id", right_on="id", how="inner") 

directors_63 = df2['director_name'].head(63)

movies_1

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4               Sam Raimi
              ...
1460      Martin Scorsese
1461          Kevin Smith
1462             Uwe Boll
1463    Richard Linklater
1464     Robert Rodriguez
Name: director_name, Length: 1465, dtype: object

In [ ]:
import numpy as np

dir_indices = directors.index.to_list()
np.random.shuffle(dir_indices)
shuffled_directors = directors.loc[dir_indices].reset_index(drop=True).head(63)

merged_df = pd.merge(
    movies, 
    shuffled_directors, 
    left_on='director_id',  # Adjust this column name to match your movies csv
    right_on='id',          # Adjust this column name to match your directors csv/index name
    how='outer', 
    indicator=True          # <--- This creates the '_merge' column
)

matched_movies = merged_df[merged_df['_merge'] == 'both']
unmatched_movies = merged_df[merged_df['_merge'] == 'left_only']

print("Matched Movies Shape:", matched_movies.shape)
print("Unmatched Movies Shape:", unmatched_movies.shape)


size = 10

random_matched = matched_movies.sample(n=min(len(matched_movies), int(size/2)))
print(random_matched.shape)
random_unmatched = unmatched_movies.sample(n=min(len(unmatched_movies), int(size/2)))
print(random_unmatched.shape)


final_selection = pd.concat([random_matched, random_unmatched])[['title', 'director_name', '_merge']]

Matched Movies Shape: (77, 15)
Unmatched Movies Shape: (1388, 15)
(5, 15)
(5, 15)

In [32]:
final_selection

                                title    director_name     _merge
1022                  Ready to Rumble    Brian Robbins       both
1019                   The Shaggy Dog    Brian Robbins       both
260                        GoodFellas  Martin Scorsese       both
4                           The Abyss    James Cameron       both
6                      The Terminator    James Cameron       both
1184                    28 Days Later              NaN  left_only
462                    Now You See Me              NaN  left_only
1400                           Bernie              NaN  left_only
1483                           Saw IV              NaN  left_only
718   The Adventures of Ford Fairlane              NaN  left_only

In [1]:
import pandas as pd
import json

df_banking_data_categories = json.load(open("datasets/banking_data/categories.json", "r"))

In [6]:
categories = pd.DataFrame(df_banking_data_categories)
categories.rename(columns={0: 'category'}, inplace=True)
categories

                            category
0                       card_arrival
1                       card_linking
2                      exchange_rate
3   card_payment_wrong_exchange_rate
4          extra_charge_on_statement
..                               ...
72            cash_withdrawal_charge
73              card_about_to_expire
74           apple_pay_or_google_pay
75                verify_my_identity
76                   country_support

[77 rows x 1 columns]

In [7]:
from datasets import load_dataset

ds = load_dataset("google-research-datasets/go_emotions", "simplified")

README.md: 0.00B [00:00, ?B/s]

simplified/train-00000-of-00001.parquet:   0%|          | 0.00/2.77M [00:00<?, ?B/s]

simplified/validation-00000-of-00001.par(…):   0%|          | 0.00/350k [00:00<?, ?B/s]

simplified/test-00000-of-00001.parquet:   0%|          | 0.00/347k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/43410 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5426 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5427 [00:00<?, ? examples/s]

In [14]:
ds['test']['labels'][:100]

[[25],
 [0],
 [13],
 [15],
 [27],
 [15],
 [15],
 [15],
 [24],
 [25],
 [3, 10],
 [1, 18],
 [8],
 [0, 7],
 [14],
 [10],
 [14],
 [25, 27],
 [1],
 [15],
 [1],
 [24],
 [27],
 [27],
 [6, 27],
 [27],
 [0, 18],
 [27],
 [27],
 [7],
 [27],
 [27],
 [27],
 [20],
 [4, 27],
 [27],
 [27],
 [27],
 [27],
 [0, 1],
 [10],
 [5],
 [27],
 [27],
 [17, 26],
 [27],
 [1],
 [1],
 [27],
 [4],
 [27],
 [3, 10],
 [10, 27],
 [27],
 [14, 27],
 [27],
 [8],
 [27],
 [24],
 [15],
 [27],
 [18],
 [18],
 [27],
 [15],
 [25],
 [14],
 [6, 20],
 [9],
 [3],
 [3],
 [27],
 [27],
 [0, 1],
 [5, 20],
 [10, 18],
 [0, 22],
 [14],
 [4],
 [2, 3],
 [0],
 [20],
 [15],
 [7, 27],
 [3],
 [6],
 [10],
 [27],
 [0],
 [15],
 [7, 17],
 [10],
 [27],
 [22],
 [26],
 [27],
 [14],
 [13, 27],
 [27],
 [5, 18]]